
Context:

[Bump version.
Lemmih <lemmih@vo.com>**20081109134303] 

[dooh, I forgot to kill the ktid thread in TimeOut.hs
marco-oweber@gmx.de**20080918235501] 

[support for base 5 (extensible exceptions) and nesting timeouts
marco-oweber@gmx.de**20080918012057
 withTimeOut functions behave slightly different now:
 They always rethrow exceptions other than the own internal ones.
 Prior to this patch withTimeOutMaybe returned Nothing on any non catched
 Exception
] 

[removed HAppS.Util.Exception
marco-oweber@gmx.de**20080917151726
 The corresponding patch must be applied to HAppS-Server because the module has
 been used in this one place only.
 catchSome doesn't tell you much about when to use
 All exceptions are catched in rloop anyway
 
] 

[Fix haddock annotation.
Lemmih <lemmih@vo.com>**20080229151217] 

[Cabal wibbles.
Lemmih <lemmih@vo.com>**20080222230653] 

[TAG 0.9.2
Lemmih <lemmih@vo.com>**20080222225437] 
